site_name: "Linux Commands"

theme:
  name: "material"
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - palette.toggle
    - navigation.footer
    - navigation.sidebar
    - navigation.expand

nav:
  - Home: index.md
  - Commands:
      - File Management:
          - ls: commands/file_management/ls.md
          - pwd: commands/file_management/pwd.md
          - cp: commands/file_management/cp.md

markdown_extensions:
  - toc:
      permalink: True
  - codehilite

repo_url: "https://github.com/SnakeByteDev/linux-commands"

extra:
  generator: false